[lib]
name = "nitrogfx"
path = "src/lib.rs"

[package]
name = "nitrogfx"
edition = "2021"

[dependencies]
png = "0.17.15"
serde = { version = "1.0.217", features = ["serde_derive"] }
serde_json = "1.0.138"

[dev-dependencies]
rayon = "1.10.0"
